server:
  port: 8083

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: 12345
  config:
    import: "optional:configserver:http://localhost:8888"

  rabbitmq:
    username: guest
    password: guest