version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 3s
      retries: 10

  # vault:
  #   image: hashicorp/vault:1.17
  #   container_name: vault
  #   ports:
  #     - "8200:8200"
  #   environment:
  #     VAULT_ADDR: https://127.0.0.1:8200
  #     VAULT_API_ADDR: https://vault:8200
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - vault_data:/vault/data
  #     - ./infrastructure/vault/config:/vault/config:ro
  #     - ./infrastructure/vault/tls:/vault/tls:ro
  #   command: vault server -config=/vault/config/vault.hcl
  #   healthcheck:
  #     test: ["CMD", "vault", "status", "-tls-skip-verify"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10

  vault-init:
    image: hashicorp/vault:1.17
    container_name: vault-init
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-root-token
    volumes:
      - ./infrastructure/vault:/vault/init:ro
    entrypoint: /bin/sh
    command: /vault/init/vault-init.sh
    restart: "no"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  rabbitmq_data:
  # vault_data: