server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: my-secret-key-which-should-be-long