server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: my-secret-key-which-should-be-long