server:
  port: 8081

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: postgres
    password: 12345
  config:
    import: "optional:configserver:http://localhost:8888"
  rabbitmq:
    username: guest
    password: guest