server:
  port: 8081

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%X{correlationId}] %logger{36} : %msg%n"
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.engine.jdbc.env.internal: DEBUG

