spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: http://${BOOK_SERVICE_HOST:book-service}:8081
              predicates:
                - Path=/api/v1/books/**

            - id: borrowing-service
              uri: http://${BORROWING_SERVICE_HOST:borrowing-service}:8082
              predicates:
                - Path=/api/v1/borrowings/**

            - id: notification-service
              uri: http://${NOTIFICATION_SERVICE_HOST:notification-service}:8083
              predicates:
                - Path=/api/v1/notifications/**

services:
  book:
    base-url: http://${BOOK_SERVICE_HOST:book-service}:8081
  borrowing:
    base-url: http://${BORROWING_SERVICE_HOST:borrowing-service}:8082
  notification:
    base-url: http://${NOTIFICATION_SERVICE_HOST:notification-service}:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info
