server:
  port: 8082

spring:
  application:
    name: borrowing-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888},optional:vault://"
  cloud:
    vault:
      uri: ${VAULT_URI:http://localhost:8200}
      authentication: token
      token: ${VAULT_TOKEN:dev-root-token}

#  cloud:
#    vault:
#      uri: ${VAULT_URI}
#      authentication: approle
#      app-role:
#        role-id: ${VAULT_ROLE_ID}
#        secret-id: ${VAULT_SECRET_ID}
#        app-role-path: approle
#      ssl:
#        trust-store: classpath:vault-truststore.jks
#        trust-store-password: ${VAULT_TRUSTSTORE_PASSWORD}
