server:
  port: 8082

spring:
  application:
    name: borrowing-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  datasource:
    password: 12345
  rabbitmq:
    username: guest
    password: guest
