server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    include: ${CONFIG_SERVER_BACKEND:native}
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:../${CONFIG_SEARCH_PATH:configuration}
            - file:../${CONFIG_SEARCH_PATH:configuration}/{application}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh

---
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI}
          default-label: ${SPRING_PROFILES_ACTIVE:dev}
          clone-on-start: true
          force-pull: true
