server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:../${CONFIG_SEARCH_PATH:configuration}

management:
  endpoints:
    web:
      exposure:
        include: health,info
