spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.engine.jdbc.env.internal: DEBUG
