spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/borrow
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

book-service:
  base-url: http://localhost:8081
  books-path: /api/v1/books

resilience4j:
  retry:
    instances:
      bookService:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
  circuitbreaker:
    instances:
      bookService:
        sliding-window-type: count_based
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.engine.jdbc.env.internal: DEBUG
